# Deploy generated dist/ to GitHub Pages
name: Deploy site to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install npm deps (if any)
        run: npm install --no-audit --no-fund
        # continue even if there are no deps

      - name: Run site generator
        run: npm run generate

      - name: Debug — list repo root
        run: |
          echo "Repo root files:"
          ls -la
          echo
          if [ -d dist ]; then
            echo "dist contents:"
            ls -la dist
          else
            echo "Warning: dist/ not found"
            find . -maxdepth 2 -type d -print
          fi

      - name: Upload site to GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
